[build]
  command = "corepack enable && yarn install && yarn build"

# No publish directory specified â€” the plugin will handle it automatically

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  NODE_VERSION = "22.21.1"
